version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  product-catalog:
    build:
      context: ./product_catalog
      dockerfile: Dockerfile

  user-management:
    build:
      context: ./user_management
      dockerfile: Dockerfile

  order-processing:
    build:
      context: ./order_processing
      dockerfile: Dockerfile
