#!/usr/bin/env sh

echo "=== List Users ==="
curl localhost:8080/users | jq

echo
echo
echo "=== List Products ==="
curl localhost:8080/products | jq

echo
echo
echo "=== List Orders (should be empty) ==="
curl localhost:8080/orders | jq

for data in \
  '{"user_id":1,"cart":[{"product_id":1,"amount":2},{"product_id":2,"amount":1}]}' \
  '{"user_id":2,"cart":[{"product_id":2,"amount":3},{"product_id":4,"amount":2}]}' \
  '{"user_id":3,"cart":[{"product_id":1,"amount":1},{"product_id":3,"amount":5}]}'
do
  echo
  echo
  echo "=== Create Order ==="
  echo $data | jq
  curl -X POST localhost:8080/orders -H "Content-Type: application/json" -d "$data"
done

echo
echo
echo "=== List Orders ==="
curl localhost:8080/orders | jq
