
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Damy Metzke", email = "damy.metzke@gmail.com"},
]
dependencies = [
    "flask>=2.3.2",
    "requests>=2.31.0",
]
requires-python = ">=3.11"
license = {text = "None"}
